pub(super) mod addyio;
pub(super) mod duckduckgo;
pub(super) mod fastmail;
pub(super) mod firefox;
pub(super) mod forwardemail;
pub(super) mod simplelogin;

fn format_description(website: &Option<String>) -> String {
    let description = website
        .as_ref()
        .map(|w| format!("Website: {w}. "))
        .unwrap_or_default();
    format!("{description}Generated by Bitwarden.")
}

fn format_description_ff(website: &Option<String>) -> String {
    let description = website
        .as_ref()
        .map(|w| format!("{w} - "))
        .unwrap_or_default();
    format!("{description}Generated by Bitwarden.")
}
