class SecretsClient
  @command_runner: CommandRunner

  def create: (key: String, note: String, organization_id: String, project_ids: Array[String], value: String) -> Hash
  def delete_secret: (ids: Array[String]) -> Hash
  def get: (id: String)  -> Hash
  def get_by_ids: (ids: Array[String]) -> Hashmap
  def list: (organization_id: String) -> Hash
  def update: (id: String, key: String, note: String, organization_id: String, project_ids: Array[String], value: String) -> Hash
end
