class SecretsClient
  @command_runner: CommandRunner

  def create: -> JSON

  def delete_secret: -> JSON

  def get: -> JSON

  def get_by_ids: -> JSON

  def list: -> JSON

  def update: -> JSON
end
