module BitwardenSDKSecrets
  class BitwardenSettings
    @api_url: untyped

    @identity_url: untyped

    attr_accessor api_url: untyped

    attr_accessor identity_url: untyped

    def initialize: (untyped api_url, untyped identity_url) -> void
  end

  class BitwardenClient
    @bitwarden: untyped

    @handle: untyped

    @command_runner: untyped

    @projects: untyped

    @secrets: untyped

    @auth: untyped

    attr_reader bitwarden: untyped

    attr_reader projects: untyped

    attr_reader secrets: untyped

    attr_reader auth: untyped

    def initialize: (untyped bitwarden_settings) -> void

    def free_mem: () -> untyped
  end
end
