require_relative '../lib/schemas'

class BitwardenClient
  @command_runner: CommandRunner

  attr_reader bitwarden: Module
  attr_reader project_client: ProjectsClient
  attr_reader secrets_client: SecretsClient

  def initialize: (BitwardenSettings) -> void
  def login_access_token: (String) -> JSON
  def free_mem: () -> nil
end
