module BitwardenSDKSecrets
  class CommandRunner
    @bitwarden_sdk: untyped

    @handle: untyped

    def initialize: (untyped bitwarden_sdk, untyped handle) -> void

    # @param [Dry-Struct] cmd
    def run: (untyped cmd) -> untyped
  end
end
