module BitwardenSDKSecrets
  class SecretsClient
    @command_runner: untyped

    def initialize: (untyped command_runner) -> void

    def get: (untyped id) -> untyped

    def get_by_ids: (untyped ids) -> untyped

    def sync: (untyped organization_id, untyped last_synced_date) -> untyped

    def create: (untyped organization_id, untyped key, untyped value, untyped note, untyped project_ids) -> untyped

    def list: (untyped organization_id) -> untyped

    def update: (untyped organization_id, untyped id, untyped key, untyped value, untyped note, untyped project_ids) -> untyped

    def delete: (untyped ids) -> untyped

    private

    def error_response: (untyped response) -> (untyped | nil | untyped)

    def create_command: (untyped commands) -> untyped

    def run_command: (untyped command) -> untyped
  end
end
