[bindings.kotlin]
package_name = "com.bitwarden.vault"
generate_immutable_records = true
android = true

[bindings.swift]
ffi_module_name = "BitwardenVaultFFI"
module_name = "BitwardenVault"
generate_immutable_records = true
