/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccessPolicyUpdateRequest {
    #[serde(rename = "read")]
    pub read: bool,
    #[serde(rename = "write")]
    pub write: bool,
}

impl AccessPolicyUpdateRequest {
    pub fn new(read: bool, write: bool) -> AccessPolicyUpdateRequest {
        AccessPolicyUpdateRequest { read, write }
    }
}
