/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

///
#[repr(i64)]
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    serde_repr::Serialize_repr,
    serde_repr::Deserialize_repr,
)]
pub enum Algorithm {
    RS1 = -65535,
    RS512 = -259,
    RS384 = -258,
    RS256 = -257,
    ES256K = -47,
    PS512 = -39,
    PS384 = -38,
    PS256 = -37,
    ES512 = -36,
    ES384 = -35,
    EdDSA = -8,
    ES256 = -7,
}

impl std::fmt::Display for Algorithm {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RS1 => write!(f, "-65535"),
            Self::RS512 => write!(f, "-259"),
            Self::RS384 => write!(f, "-258"),
            Self::RS256 => write!(f, "-257"),
            Self::ES256K => write!(f, "-47"),
            Self::PS512 => write!(f, "-39"),
            Self::PS384 => write!(f, "-38"),
            Self::PS256 => write!(f, "-37"),
            Self::ES512 => write!(f, "-36"),
            Self::ES384 => write!(f, "-35"),
            Self::EdDSA => write!(f, "-8"),
            Self::ES256 => write!(f, "-7"),
        }
    }
}

impl Default for Algorithm {
    fn default() -> Algorithm {
        Self::RS1
    }
}
