/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};
use serde_with::serde_as;

use crate::models;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssertionResponse {
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "authenticatorData", skip_serializing_if = "Option::is_none")]
    pub authenticator_data: Option<Vec<u8>>,
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<Vec<u8>>,
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "clientDataJSON", skip_serializing_if = "Option::is_none")]
    pub client_data_json: Option<Vec<u8>>,
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "userHandle", skip_serializing_if = "Option::is_none")]
    pub user_handle: Option<Vec<u8>>,
}

impl AssertionResponse {
    pub fn new() -> AssertionResponse {
        AssertionResponse {
            authenticator_data: None,
            signature: None,
            client_data_json: None,
            user_handle: None,
        }
    }
}
