/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatorSelection {
    #[serde(
        rename = "authenticatorAttachment",
        skip_serializing_if = "Option::is_none"
    )]
    pub authenticator_attachment: Option<crate::models::AuthenticatorAttachment>,
    #[serde(rename = "requireResidentKey", skip_serializing_if = "Option::is_none")]
    pub require_resident_key: Option<bool>,
    #[serde(rename = "userVerification", skip_serializing_if = "Option::is_none")]
    pub user_verification: Option<crate::models::UserVerificationRequirement>,
}

impl AuthenticatorSelection {
    pub fn new() -> AuthenticatorSelection {
        AuthenticatorSelection {
            authenticator_attachment: None,
            require_resident_key: None,
            user_verification: None,
        }
    }
}
