/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthRequestUpdateRequestModel {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "masterPasswordHash", skip_serializing_if = "Option::is_none")]
    pub master_password_hash: Option<String>,
    #[serde(rename = "deviceIdentifier")]
    pub device_identifier: String,
    #[serde(rename = "requestApproved")]
    pub request_approved: bool,
}

impl AuthRequestUpdateRequestModel {
    pub fn new(device_identifier: String, request_approved: bool) -> AuthRequestUpdateRequestModel {
        AuthRequestUpdateRequestModel {
            key: None,
            master_password_hash: None,
            device_identifier,
            request_approved,
        }
    }
}
