/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatorAssertionRawResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "rawId", skip_serializing_if = "Option::is_none")]
    pub raw_id: Option<String>,
    #[serde(rename = "response", skip_serializing_if = "Option::is_none")]
    pub response: Option<Box<crate::models::AssertionResponse>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::PublicKeyCredentialType>,
    #[serde(rename = "extensions", skip_serializing_if = "Option::is_none")]
    pub extensions: Option<Box<crate::models::AuthenticationExtensionsClientOutputs>>,
}

impl AuthenticatorAssertionRawResponse {
    pub fn new() -> AuthenticatorAssertionRawResponse {
        AuthenticatorAssertionRawResponse {
            id: None,
            raw_id: None,
            response: None,
            r#type: None,
            extensions: None,
        }
    }
}
