/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CipherDetailsResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>, // Not sure what this is?

    // MetaData structure is owned by the Server
    // This doesn't necessarily need to be in it's own struct
    #[serde(rename = "metaData")]
    pub meta_data: CipherDetailsMetaDataResponseModel,

    // Data structure is owned by the Client
    #[serde(rename = "data")]
    pub data: serde_json::Value,
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CipherDetailsMetaDataResponseModel {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "organizationId", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<uuid::Uuid>,
    #[serde(rename = "collectionIds", skip_serializing_if = "Option::is_none")]
    pub collection_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "folderId", skip_serializing_if = "Option::is_none")]
    pub folder_id: Option<uuid::Uuid>,
    #[serde(rename = "viewPassword", skip_serializing_if = "Option::is_none")]
    pub view_password: Option<bool>,
    #[serde(
        rename = "organizationUseTotp",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_use_totp: Option<bool>,
    #[serde(rename = "revisionDate", skip_serializing_if = "Option::is_none")]
    pub revision_date: Option<String>,
    #[serde(rename = "creationDate", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    #[serde(rename = "deletedDate", skip_serializing_if = "Option::is_none")]
    pub deleted_date: Option<String>,
}

impl CipherDetailsResponseModel {
    pub fn new() -> CipherDetailsResponseModel {
        CipherDetailsResponseModel {
            object: None,
            meta_data: Default::default(),
            data: Default::default(),
        }
    }
}
