/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CipherCreateRequestModel {
    #[serde(rename = "collectionIds", skip_serializing_if = "Option::is_none")]
    pub collection_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "cipher")]
    pub cipher: Box<crate::models::CipherRequestModel>,
}

impl CipherCreateRequestModel {
    pub fn new(cipher: crate::models::CipherRequestModel) -> CipherCreateRequestModel {
        CipherCreateRequestModel {
            collection_ids: None,
            cipher: Box::new(cipher),
        }
    }
}
