/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum CipherType {
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
}

impl ToString for CipherType {
    fn to_string(&self) -> String {
        match self {
            Self::_1 => String::from("1"),
            Self::_2 => String::from("2"),
            Self::_3 => String::from("3"),
            Self::_4 => String::from("4"),
        }
    }
}

impl Default for CipherType {
    fn default() -> CipherType {
        Self::_1
    }
}
