/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteRecoverRequestModel {
    #[serde(rename = "email")]
    pub email: String,
}

impl DeleteRecoverRequestModel {
    pub fn new(email: String) -> DeleteRecoverRequestModel {
        DeleteRecoverRequestModel { email }
    }
}
