/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceKeysUpdateRequestModel {
    #[serde(rename = "encryptedPublicKey")]
    pub encrypted_public_key: String,
    #[serde(rename = "encryptedUserKey")]
    pub encrypted_user_key: String,
}

impl DeviceKeysUpdateRequestModel {
    pub fn new(
        encrypted_public_key: String,
        encrypted_user_key: String,
    ) -> DeviceKeysUpdateRequestModel {
        DeviceKeysUpdateRequestModel {
            encrypted_public_key,
            encrypted_user_key,
        }
    }
}
