/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceTokenRequestModel {
    #[serde(rename = "pushToken", skip_serializing_if = "Option::is_none")]
    pub push_token: Option<String>,
}

impl DeviceTokenRequestModel {
    pub fn new() -> DeviceTokenRequestModel {
        DeviceTokenRequestModel { push_token: None }
    }
}
