/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeviceVerificationResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(
        rename = "isDeviceVerificationSectionEnabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_device_verification_section_enabled: Option<bool>,
    #[serde(
        rename = "unknownDeviceVerificationEnabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub unknown_device_verification_enabled: Option<bool>,
}

impl DeviceVerificationResponseModel {
    pub fn new() -> DeviceVerificationResponseModel {
        DeviceVerificationResponseModel {
            object: None,
            is_device_verification_section_enabled: None,
            unknown_device_verification_enabled: None,
        }
    }
}
