/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum DeviceType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
    _6 = 6,
    _7 = 7,
    _8 = 8,
    _9 = 9,
    _10 = 10,
    _11 = 11,
    _12 = 12,
    _13 = 13,
    _14 = 14,
    _15 = 15,
    _16 = 16,
    _17 = 17,
    _18 = 18,
    _19 = 19,
    _20 = 20,
    _21 = 21,
    _22 = 22,
}

impl ToString for DeviceType {
    fn to_string(&self) -> String {
        match self {
            Self::_0 => String::from("0"),
            Self::_1 => String::from("1"),
            Self::_2 => String::from("2"),
            Self::_3 => String::from("3"),
            Self::_4 => String::from("4"),
            Self::_5 => String::from("5"),
            Self::_6 => String::from("6"),
            Self::_7 => String::from("7"),
            Self::_8 => String::from("8"),
            Self::_9 => String::from("9"),
            Self::_10 => String::from("10"),
            Self::_11 => String::from("11"),
            Self::_12 => String::from("12"),
            Self::_13 => String::from("13"),
            Self::_14 => String::from("14"),
            Self::_15 => String::from("15"),
            Self::_16 => String::from("16"),
            Self::_17 => String::from("17"),
            Self::_18 => String::from("18"),
            Self::_19 => String::from("19"),
            Self::_20 => String::from("20"),
            Self::_21 => String::from("21"),
            Self::_22 => String::from("22"),
        }
    }
}

impl Default for DeviceType {
    fn default() -> DeviceType {
        Self::_0
    }
}
