/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DomainsResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "equivalentDomains", skip_serializing_if = "Option::is_none")]
    pub equivalent_domains: Option<Vec<Vec<String>>>,
    #[serde(
        rename = "globalEquivalentDomains",
        skip_serializing_if = "Option::is_none"
    )]
    pub global_equivalent_domains: Option<Vec<crate::models::GlobalDomains>>,
}

impl DomainsResponseModel {
    pub fn new() -> DomainsResponseModel {
        DomainsResponseModel {
            object: None,
            equivalent_domains: None,
            global_equivalent_domains: None,
        }
    }
}
