/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum EventSystemUser {
    Variant1 = 1,
    Variant2 = 2,
}

impl ToString for EventSystemUser {
    fn to_string(&self) -> String {
        match self {
            Self::Variant1 => String::from("1"),
            Self::Variant2 => String::from("2"),
        }
    }
}

impl Default for EventSystemUser {
    fn default() -> EventSystemUser {
        Self::Variant1
    }
}
