/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GrantedAccessPolicyRequest {
    #[serde(rename = "grantedId")]
    pub granted_id: uuid::Uuid,
    #[serde(rename = "read")]
    pub read: bool,
    #[serde(rename = "write")]
    pub write: bool,
}

impl GrantedAccessPolicyRequest {
    pub fn new(granted_id: uuid::Uuid, read: bool, write: bool) -> GrantedAccessPolicyRequest {
        GrantedAccessPolicyRequest {
            granted_id,
            read,
            write,
        }
    }
}
