/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum MemberDecryptionType {
    MasterPassword = 0,
    KeyConnector = 1,
    TrustedDeviceEncryption = 2,

    #[serde(other)]
    UnknownValue = -1337,
}

impl ToString for MemberDecryptionType {
    fn to_string(&self) -> String {
        match self {
            Self::MasterPassword => String::from("0"),
            Self::KeyConnector => String::from("1"),
            Self::TrustedDeviceEncryption => String::from("2"),
            Self::UnknownValue => String::from("UnknownValue"),
        }
    }
}

impl Default for MemberDecryptionType {
    fn default() -> MemberDecryptionType {
        Self::MasterPassword
    }
}
