/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

///
#[repr(i64)]
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    serde_repr::Serialize_repr,
    serde_repr::Deserialize_repr,
)]
pub enum OpenIdConnectRedirectBehavior {
    RedirectGet = 0,
    FormPost = 1,
}

impl std::fmt::Display for OpenIdConnectRedirectBehavior {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RedirectGet => write!(f, "0"),
            Self::FormPost => write!(f, "1"),
        }
    }
}

impl Default for OpenIdConnectRedirectBehavior {
    fn default() -> OpenIdConnectRedirectBehavior {
        Self::RedirectGet
    }
}
