/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganizationUserAcceptInitRequestModel {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "keys")]
    pub keys: Box<crate::models::OrganizationKeysRequestModel>,
    #[serde(rename = "collectionName", skip_serializing_if = "Option::is_none")]
    pub collection_name: Option<String>,
}

impl OrganizationUserAcceptInitRequestModel {
    pub fn new(
        token: String,
        key: String,
        keys: crate::models::OrganizationKeysRequestModel,
    ) -> OrganizationUserAcceptInitRequestModel {
        OrganizationUserAcceptInitRequestModel {
            token,
            key,
            keys: Box::new(keys),
            collection_name: None,
        }
    }
}
