/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationUserBulkConfirmRequestModelEntry {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "key")]
    pub key: String,
}

impl OrganizationUserBulkConfirmRequestModelEntry {
    pub fn new(id: uuid::Uuid, key: String) -> OrganizationUserBulkConfirmRequestModelEntry {
        OrganizationUserBulkConfirmRequestModelEntry { id, key }
    }
}
