/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganizationSponsorshipSyncRequestModel {
    #[serde(rename = "billingSyncKey", skip_serializing_if = "Option::is_none")]
    pub billing_sync_key: Option<String>,
    #[serde(
        rename = "sponsoringOrganizationCloudId",
        skip_serializing_if = "Option::is_none"
    )]
    pub sponsoring_organization_cloud_id: Option<uuid::Uuid>,
    #[serde(rename = "sponsorshipsBatch", skip_serializing_if = "Option::is_none")]
    pub sponsorships_batch: Option<Vec<crate::models::OrganizationSponsorshipRequestModel>>,
}

impl OrganizationSponsorshipSyncRequestModel {
    pub fn new() -> OrganizationSponsorshipSyncRequestModel {
        OrganizationSponsorshipSyncRequestModel {
            billing_sync_key: None,
            sponsoring_organization_cloud_id: None,
            sponsorships_batch: None,
        }
    }
}
