/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrganizationDomainResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "organizationId", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<uuid::Uuid>,
    #[serde(rename = "txt", skip_serializing_if = "Option::is_none")]
    pub txt: Option<String>,
    #[serde(rename = "domainName", skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<String>,
    #[serde(rename = "creationDate", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    #[serde(rename = "nextRunDate", skip_serializing_if = "Option::is_none")]
    pub next_run_date: Option<String>,
    #[serde(rename = "jobRunCount", skip_serializing_if = "Option::is_none")]
    pub job_run_count: Option<i32>,
    #[serde(rename = "verifiedDate", skip_serializing_if = "Option::is_none")]
    pub verified_date: Option<String>,
    #[serde(rename = "lastCheckedDate", skip_serializing_if = "Option::is_none")]
    pub last_checked_date: Option<String>,
}

impl OrganizationDomainResponseModel {
    pub fn new() -> OrganizationDomainResponseModel {
        OrganizationDomainResponseModel {
            object: None,
            id: None,
            organization_id: None,
            txt: None,
            domain_name: None,
            creation_date: None,
            next_run_date: None,
            job_run_count: None,
            verified_date: None,
            last_checked_date: None,
        }
    }
}
