/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum PaymentMethodType {
    Card = 0,
    BankAccount = 1,
    PayPal = 2,
    BitPay = 3,
    Credit = 4,
    WireTransfer = 5,
    Check = 8,
    None = 255,
}

impl ToString for PaymentMethodType {
    fn to_string(&self) -> String {
        match self {
            Self::Card => String::from("0"),
            Self::BankAccount => String::from("1"),
            Self::PayPal => String::from("2"),
            Self::BitPay => String::from("3"),
            Self::Credit => String::from("4"),
            Self::WireTransfer => String::from("5"),
            Self::Check => String::from("8"),
            Self::None => String::from("255"),
        }
    }
}

impl Default for PaymentMethodType {
    fn default() -> PaymentMethodType {
        Self::Card
    }
}
