/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PotentialGranteeResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "currentUserInGroup", skip_serializing_if = "Option::is_none")]
    pub current_user_in_group: Option<bool>,
    #[serde(rename = "currentUser", skip_serializing_if = "Option::is_none")]
    pub current_user: Option<bool>,
}

impl PotentialGranteeResponseModel {
    pub fn new() -> PotentialGranteeResponseModel {
        PotentialGranteeResponseModel {
            object: None,
            id: None,
            name: None,
            r#type: None,
            email: None,
            current_user_in_group: None,
            current_user: None,
        }
    }
}
