/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum ProductType {
    Free = 0,
    Families = 1,
    Teams = 2,
    Enterprise = 3,
    TeamsStarter = 4,

    #[serde(other)]
    UnknownValue = -1337,
}

impl ToString for ProductType {
    fn to_string(&self) -> String {
        match self {
            Self::Free => String::from("0"),
            Self::Families => String::from("1"),
            Self::Teams => String::from("2"),
            Self::Enterprise => String::from("3"),
            Self::TeamsStarter => String::from("4"),
            Self::UnknownValue => String::from("UnknownValue"),
        }
    }
}

impl Default for ProductType {
    fn default() -> ProductType {
        Self::Free
    }
}
