/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectUpdateRequestModel {
    #[serde(rename = "name")]
    pub name: String,
}

impl ProjectUpdateRequestModel {
    pub fn new(name: String) -> ProjectUpdateRequestModel {
        ProjectUpdateRequestModel { name }
    }
}
