/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectAccessPoliciesResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "userAccessPolicies", skip_serializing_if = "Option::is_none")]
    pub user_access_policies: Option<Vec<crate::models::UserProjectAccessPolicyResponseModel>>,
    #[serde(
        rename = "groupAccessPolicies",
        skip_serializing_if = "Option::is_none"
    )]
    pub group_access_policies: Option<Vec<crate::models::GroupProjectAccessPolicyResponseModel>>,
    #[serde(
        rename = "serviceAccountAccessPolicies",
        skip_serializing_if = "Option::is_none"
    )]
    pub service_account_access_policies:
        Option<Vec<crate::models::ServiceAccountProjectAccessPolicyResponseModel>>,
}

impl ProjectAccessPoliciesResponseModel {
    pub fn new() -> ProjectAccessPoliciesResponseModel {
        ProjectAccessPoliciesResponseModel {
            object: None,
            user_access_policies: None,
            group_access_policies: None,
            service_account_access_policies: None,
        }
    }
}
