/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProviderResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "businessName", skip_serializing_if = "Option::is_none")]
    pub business_name: Option<String>,
    #[serde(rename = "businessAddress1", skip_serializing_if = "Option::is_none")]
    pub business_address1: Option<String>,
    #[serde(rename = "businessAddress2", skip_serializing_if = "Option::is_none")]
    pub business_address2: Option<String>,
    #[serde(rename = "businessAddress3", skip_serializing_if = "Option::is_none")]
    pub business_address3: Option<String>,
    #[serde(rename = "businessCountry", skip_serializing_if = "Option::is_none")]
    pub business_country: Option<String>,
    #[serde(rename = "businessTaxNumber", skip_serializing_if = "Option::is_none")]
    pub business_tax_number: Option<String>,
    #[serde(rename = "billingEmail", skip_serializing_if = "Option::is_none")]
    pub billing_email: Option<String>,
}

impl ProviderResponseModel {
    pub fn new() -> ProviderResponseModel {
        ProviderResponseModel {
            object: None,
            id: None,
            name: None,
            business_name: None,
            business_address1: None,
            business_address2: None,
            business_address3: None,
            business_country: None,
            business_tax_number: None,
            billing_email: None,
        }
    }
}
