/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProviderUserInviteRequestModel {
    #[serde(rename = "emails")]
    pub emails: Vec<String>,
    #[serde(rename = "type")]
    pub _type: crate::models::ProviderUserType,
}

impl ProviderUserInviteRequestModel {
    pub fn new(
        emails: Vec<String>,
        _type: crate::models::ProviderUserType,
    ) -> ProviderUserInviteRequestModel {
        ProviderUserInviteRequestModel { emails, _type }
    }
}
