/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderOrganizationAddRequestModel {
    #[serde(rename = "organizationId")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "key")]
    pub key: String,
}

impl ProviderOrganizationAddRequestModel {
    pub fn new(organization_id: uuid::Uuid, key: String) -> ProviderOrganizationAddRequestModel {
        ProviderOrganizationAddRequestModel {
            organization_id,
            key,
        }
    }
}
