/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PushRegistrationRequestModel {
    #[serde(rename = "deviceId")]
    pub device_id: String,
    #[serde(rename = "pushToken")]
    pub push_token: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "type")]
    pub r#type: crate::models::DeviceType,
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl PushRegistrationRequestModel {
    pub fn new(
        device_id: String,
        push_token: String,
        user_id: String,
        r#type: crate::models::DeviceType,
        identifier: String,
    ) -> PushRegistrationRequestModel {
        PushRegistrationRequestModel {
            device_id,
            push_token,
            user_id,
            r#type,
            identifier,
        }
    }
}
