/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestSmAccessRequestModel {
    #[serde(rename = "organizationId")]
    pub organization_id: uuid::Uuid,
    #[serde(rename = "emailContent")]
    pub email_content: String,
}

impl RequestSmAccessRequestModel {
    pub fn new(organization_id: uuid::Uuid, email_content: String) -> RequestSmAccessRequestModel {
        RequestSmAccessRequestModel {
            organization_id,
            email_content,
        }
    }
}
