/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum Saml2BindingType {
    HttpRedirect = 1,
    HttpPost = 2,

    #[serde(other)]
    UnknownValue = -1337,
}

impl ToString for Saml2BindingType {
    fn to_string(&self) -> String {
        match self {
            Self::HttpRedirect => String::from("1"),
            Self::HttpPost => String::from("2"),
            Self::UnknownValue => String::from("UnknownValue"),
        }
    }
}

impl Default for Saml2BindingType {
    fn default() -> Saml2BindingType {
        Self::HttpRedirect
    }
}
