/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum Saml2BindingType {
    _1 = 1,
    _2 = 2,
}

impl ToString for Saml2BindingType {
    fn to_string(&self) -> String {
        match self {
            Self::_1 => String::from("1"),
            Self::_2 => String::from("2"),
        }
    }
}

impl Default for Saml2BindingType {
    fn default() -> Saml2BindingType {
        Self::_1
    }
}
