/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SelectionReadOnlyRequestModel {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(rename = "hidePasswords", skip_serializing_if = "Option::is_none")]
    pub hide_passwords: Option<bool>,
}

impl SelectionReadOnlyRequestModel {
    pub fn new(id: String) -> SelectionReadOnlyRequestModel {
        SelectionReadOnlyRequestModel {
            id,
            read_only: None,
            hide_passwords: None,
        }
    }
}
