/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAccountProjectAccessPolicyPermissionDetailsResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "accessPolicy", skip_serializing_if = "Option::is_none")]
    pub access_policy: Option<Box<crate::models::ServiceAccountProjectAccessPolicyResponseModel>>,
    #[serde(rename = "hasPermission", skip_serializing_if = "Option::is_none")]
    pub has_permission: Option<bool>,
}

impl ServiceAccountProjectAccessPolicyPermissionDetailsResponseModel {
    pub fn new() -> ServiceAccountProjectAccessPolicyPermissionDetailsResponseModel {
        ServiceAccountProjectAccessPolicyPermissionDetailsResponseModel {
            object: None,
            access_policy: None,
            has_permission: None,
        }
    }
}
