/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

///
#[repr(i64)]
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    serde_repr::Serialize_repr,
    serde_repr::Deserialize_repr,
)]
pub enum TransactionType {
    Charge = 0,
    Credit = 1,
    PromotionalCredit = 2,
    ReferralCredit = 3,
    Refund = 4,
}

impl std::fmt::Display for TransactionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Charge => write!(f, "0"),
            Self::Credit => write!(f, "1"),
            Self::PromotionalCredit => write!(f, "2"),
            Self::ReferralCredit => write!(f, "3"),
            Self::Refund => write!(f, "4"),
        }
    }
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::Charge
    }
}
