/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TwoFactorDuoResponseModel {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "secretKey", skip_serializing_if = "Option::is_none")]
    pub secret_key: Option<String>,
    #[serde(rename = "integrationKey", skip_serializing_if = "Option::is_none")]
    pub integration_key: Option<String>,
}

impl TwoFactorDuoResponseModel {
    pub fn new() -> TwoFactorDuoResponseModel {
        TwoFactorDuoResponseModel {
            object: None,
            enabled: None,
            host: None,
            secret_key: None,
            integration_key: None,
        }
    }
}
