/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateKeyRequestModel {
    #[serde(rename = "masterPasswordHash")]
    pub master_password_hash: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "privateKey")]
    pub private_key: String,
    #[serde(rename = "ciphers", skip_serializing_if = "Option::is_none")]
    pub ciphers: Option<Vec<crate::models::CipherWithIdRequestModel>>,
    #[serde(rename = "folders", skip_serializing_if = "Option::is_none")]
    pub folders: Option<Vec<crate::models::FolderWithIdRequestModel>>,
    #[serde(rename = "sends", skip_serializing_if = "Option::is_none")]
    pub sends: Option<Vec<crate::models::SendWithIdRequestModel>>,
    #[serde(
        rename = "emergencyAccessKeys",
        skip_serializing_if = "Option::is_none"
    )]
    pub emergency_access_keys: Option<Vec<crate::models::EmergencyAccessWithIdRequestModel>>,
    #[serde(rename = "resetPasswordKeys", skip_serializing_if = "Option::is_none")]
    pub reset_password_keys: Option<Vec<crate::models::ResetPasswordWithOrgIdRequestModel>>,
}

impl UpdateKeyRequestModel {
    pub fn new(
        master_password_hash: String,
        key: String,
        private_key: String,
    ) -> UpdateKeyRequestModel {
        UpdateKeyRequestModel {
            master_password_hash,
            key,
            private_key,
            ciphers: None,
            folders: None,
            sends: None,
            emergency_access_keys: None,
            reset_password_keys: None,
        }
    }
}
