/*
 * Bitwarden Internal API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum UriMatchType {
    Domain = 0,
    Host = 1,
    StartsWith = 2,
    Exact = 3,
    RegularExpression = 4,
    Never = 5,
}

impl ToString for UriMatchType {
    fn to_string(&self) -> String {
        match self {
            Self::Domain => String::from("0"),
            Self::Host => String::from("1"),
            Self::StartsWith => String::from("2"),
            Self::Exact => String::from("3"),
            Self::RegularExpression => String::from("4"),
            Self::Never => String::from("5"),
        }
    }
}

impl Default for UriMatchType {
    fn default() -> UriMatchType {
        Self::Domain
    }
}
