# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ruby-ruby.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rubocop", "~> 1.21"

gem "dry-struct", "~> 1.6"

gem "dry-types", "~> 1.7"

gem "json", "~> 2.6"

gem "ffi", "~> 1.15"
