/*
 * Bitwarden Identity
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrialSendVerificationEmailRequestModel {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "email")]
    pub email: Option<String>,
    #[serde(
        rename = "receiveMarketingEmails",
        skip_serializing_if = "Option::is_none"
    )]
    pub receive_marketing_emails: Option<bool>,
    #[serde(rename = "productTier", skip_serializing_if = "Option::is_none")]
    pub product_tier: Option<models::ProductTierType>,
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<models::ProductType>>,
}

impl TrialSendVerificationEmailRequestModel {
    pub fn new(email: Option<String>) -> TrialSendVerificationEmailRequestModel {
        TrialSendVerificationEmailRequestModel {
            name: None,
            email,
            receive_marketing_emails: None,
            product_tier: None,
            products: None,
        }
    }
}
