/*
 * Bitwarden Identity
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserVerificationRequirement {
    #[serde(rename = "required")]
    Required,
    #[serde(rename = "preferred")]
    Preferred,
    #[serde(rename = "discouraged")]
    Discouraged,
}

impl ToString for UserVerificationRequirement {
    fn to_string(&self) -> String {
        match self {
            Self::Required => String::from("required"),
            Self::Preferred => String::from("preferred"),
            Self::Discouraged => String::from("discouraged"),
        }
    }
}

impl Default for UserVerificationRequirement {
    fn default() -> UserVerificationRequirement {
        Self::Required
    }
}
