[bindings.kotlin]
package_name = "com.bitwarden.send"
generate_immutable_records = true
android = true

[bindings.swift]
ffi_module_name = "BitwardenSendFFI"
module_name = "BitwardenSend"
generate_immutable_records = true
