require_relative '../lib/schemas'

class BitwardenClient
  @command_runner: CommandRunner

  attr_reader bitwarden: Module
  attr_reader project_client: ProjectsClient
  attr_reader secrets_client: SecretsClient

  def initialize: (String, String) -> void
  def authorize: () -> JSON
  def free_mem: () -> nil
end
