require_once '../lib/extended_schemas/schemas.rbs'
require_once '../schemas.rbs'

class ProjectsClient
  @command_runner: CommandRunner
  def initialize: (command_runner: CommandRunner) -> void
  def create_project: (project_name: String, organization_id: String) -> ProjectsResponse
  def get: (project_id: String) -> ProjectsResponse
  def list_projects: (organization_id: String) -> Array(DatumElement)
  def update_project: (id: String, project_put_request_name: String, organization_id: String) -> ProjectsResponse
  def delete_projects: (ids: Array[String]) -> Array(ProjectDeleteResponse)

  private

  def create_command: (SelectiveProjectsCommand) -> SelectiveCommand
  def parse_response: (ResponseForProjectResponse) -> ResponseForProjectResponse
end
