require_once '../lib/extended_schemas/schemas.rbs'
require_once '../schemas.rbs'

class SecretsClient
  # @command_runner: CommandRunner
  def initialize: (command_runner: CommandRunner) -> void
  def get: (id: String) -> SecretResponse
  def get_by_ids: (ids: Array[String]) -> Array(SecretIdentifierResponse)
  def create: (key: String, note: String, organization_id: String, project_ids: Array[String], value: String) -> SecretResponse
  def list: (organization_id: String) -> Array(SecretIdentifierResponse)
  def update: (id: String, key: String, note: String, organization_id: String, project_ids: Array[String], value: String) -> SecretResponse
  def delete_secret: (ids: Array[String]) -> Array(SecretDeleteResponse)

  private

  def create_command: (SelectiveSecretsCommand) -> SelectiveCommand
  def parse_response: (SelectiveSecretCommand) -> ResponseForSecretResponse
end
