name: Build @bitwarden/sdk-wasm

on:
  pull_request:
  push:
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: crates/bitwarden-wasm

jobs:
  build:
    name: Building @bitwarden/sdk-wasm
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - name: Install dependencies
        run: npm i -g binaryen

      - name: Install rust
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # stable
        with:
          toolchain: 1.81.0
          targets: wasm32-unknown-unknown

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          key: wasm-cargo-cache

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.95

      - name: Build
        run: ./build.sh -r

      - name: Upload artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: sdk-bitwarden-wasm
          path: ${{ github.workspace }}/languages/js/wasm/*
          if-no-files-found: error

      - name: Set version
        if: ${{ github.ref == 'refs/heads/main' }}
        # Fetches current version from registry and uses prerelease to bump it
        run: |
          npm version --no-git-tag-version $(npm view @bitwarden/sdk-wasm@latest version)
          npm version --no-git-tag-version prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: languages/js/wasm

      - name: Publish NPM
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: languages/js/wasm
