name: Release .NET NuGet
run-name: Release .NET NuGet Package ${{ inputs.release_type }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Options"
        required: true
        default: "Release"
        type: choice
        options:
          - Release
          - Dry Run

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Branch check
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/main" ]]; then
            echo "==================================="
            echo "[!] Can only release from the 'main' branch"
            echo "==================================="
            exit 1
          fi

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Get version
        id: version
        run: |
          VERSION=$(xmllint --xpath 'string(/Project/PropertyGroup/Version)' languages/csharp/Bitwarden.Sdk/Bitwarden.Sdk.csproj)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  release:
    name: Create GitHub release
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download NuGet package
        uses: bitwarden/gh-actions/download-artifacts@main
        with:
          workflow: build-dotnet.yml
          workflow_conclusion: success
          branch: main
          artifacts: Bitwarden.Sdk.${{ needs.setup.outputs.version }}.nupkg
          path: ./nuget-output

      - name: Create release
        if: ${{ inputs.release_type != 'Dry Run' }}
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        env:
          PKG_VERSION: ${{ needs.setup.outputs.version }}
        with:
          commit: ${{ github.sha }}
          tag: dotnet-v${{ env.PKG_VERSION }}
          name: .NET NuGet v${{ env.PKG_VERSION }}
          body: "<insert release notes here>"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          artifacts: |
            ./nuget-output/Bitwarden.Sdk.${{ needs.setup.outputs.version }}.nupkg
